### ISSUE TITLE
5000 rows limit

### ISSUE THREAD

**Issue by andresrogers** [alvarobartt/investiny#24]
When I give a start and end date over 5000 days in difference, for example:

historical_data(investing_id=13928, from_date="09/01/2001", to_date="10/01/2022")

**Comment by alvarobartt** [comment]
Hi, @andresrogers thanks for reporting this issue! I'll explore it further and I'll chain the requests so that the output of `historical_data` when more than 5000 data points are actually the total data points requested and not just the first 5000. This issue was similar in `investpy` where you could just retrieve 19-20 years of data, which I assume should be around the number 5000 entries.

**Comment by alvarobartt** [comment]
I'm labeling this as a bug since this is not the expected behavior and it should be improved ASAP so that the returned response from `historical_data` contains actually the requested data and not just a portion of it.
