### ISSUE TITLE
Features to be implemented, if possible. 

### ISSUE THREAD

**Issue by sahg91** [alvarobartt/investiny#29]
Glad if you can add a method to get the information followng pages in a stock. 
1. Overview page info (like 52 wk Range ,P/E Ratio, Volume, Average Vol. (3m) etc)
2. Technical Anlysis page info (Like moving averages and rsi)

**Comment by alvarobartt** [comment]
Hi, @sahg91 that information is not available in the current Investing.com API that `investiny` is using, and in `investpy` that's not working, so I don't think that'll be possible, but I'll add some tutorials on how to combine `investiny` with other libraries so that you can easily calculate information for technical indicators!
